"""Rust/Python parity: the bindings must marshal an environment, never re-implement one.

CLAUDE.md §3 constraint (b) says the bindings add no reward, termination, or
physics behavior of their own. That is a claim about behavior, so it needs a
behavioral test: drive the same task, from the same seed, through the same
action sequence, on both sides, and demand the observation and reward streams be
*identical*.

The reference is computed at test time by `bindings/python/examples/reference_rollout.rs`
rather than stored as a fixture. A checked-in expectations file would have to be
regenerated by hand, which is the stale-artifact failure mode that also makes a
stale `.so` so confusing — it would go on passing after the thing it describes
had changed.

Floats are compared with `==`, deliberately, not `pytest.approx`. Both sides run
identical Rust on identical inputs; there is no numerical process here for a
tolerance to absorb, so any inequality means they are not in fact the same
environment. (`reference_rollout` widens each f32 to f64 before printing so the
JSON round-trip cannot introduce a difference of its own.)
"""

import json
import os
import pathlib
import subprocess

import pytest

import ml_planes

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
MANIFEST = REPO_ROOT / "bindings" / "python" / "Cargo.toml"


def reference_rollout(task: str, seed: int, steps: int, pattern: str) -> dict:
    """Run the Rust-side rollout and return its trace.

    `CARGO_TARGET_DIR` is pinned for the same reason every `just py-*` recipe
    pins it: the binding crate is its own workspace and would otherwise build a
    second, full copy of the bevy/rapier dependency tree under
    `bindings/python/target`.
    """
    env = dict(os.environ, CARGO_TARGET_DIR=str(REPO_ROOT / "target"))
    result = subprocess.run(
        [
            "cargo", "run", "--quiet",
            "--manifest-path", str(MANIFEST),
            "--example", "reference_rollout",
            "--",
            "--task", task,
            "--seed", str(seed),
            "--steps", str(steps),
            "--pattern", pattern,
        ],
        cwd=REPO_ROOT,  # the default .plane.ron path is repo-root-relative
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        pytest.fail(f"reference_rollout failed:\n{result.stderr}")
    return json.loads(result.stdout)


def replay(reference: dict) -> list[tuple]:
    """Drive `_Env` through the reference's own actions and collect the trace."""
    env = ml_planes._core._Env(reference["task"])
    assert env.observation_dim() == reference["observation_dim"]
    assert env.action_dim() == reference["action_dim"]

    env.seed(reference["seed"])
    assert env.reset() == reference["reset_obs"], "reset observation diverged"

    return [env.step(step["action"]) for step in reference["steps"]]


ROLLOUTS = [
    # (task, seed, steps, pattern)
    ("level_hold", 7, 64, "sweep"),
    ("heading_hold", 11, 64, "sweep"),
    ("orbit", 13, 64, "sweep"),
]


@pytest.mark.parametrize("task,seed,steps,pattern", ROLLOUTS)
def test_python_rollout_is_bit_identical_to_rust(task, seed, steps, pattern):
    reference = reference_rollout(task, seed, steps, pattern)
    actual = replay(reference)

    assert len(actual) == len(reference["steps"])
    for i, (expected, got) in enumerate(zip(reference["steps"], actual)):
        obs, reward, terminated, truncated, info = got
        assert obs == expected["obs"], f"step {i}: observation diverged"
        assert reward == expected["reward"], f"step {i}: reward diverged"
        assert terminated == expected["terminated"], f"step {i}: terminated diverged"
        assert truncated == expected["truncated"], f"step {i}: truncated diverged"
        assert info["episode_step"] == expected["episode_step"], f"step {i}: episode_step"


def test_a_crash_reports_terminated_not_truncated():
    """Nose-down until the ground: an absorbing `Failure`, whose value target is 0."""
    reference = reference_rollout("level_hold", 3, 4000, "dive")
    final = reference["steps"][-1]
    assert final["terminated"] is True
    assert final["truncated"] is False

    actual = replay(reference)
    assert actual[-1][2] is True, "Python side did not report terminated"
    assert actual[-1][3] is False, "Python side reported a crash as a timeout"


def test_hitting_the_step_limit_reports_truncated_not_terminated():
    """Hands off a residual env is the PID baseline flying unaided, so the episode
    survives to `max_episode_steps` and must come back as a *timeout* — the case
    whose value target bootstraps `gamma * V(s')` rather than 0."""
    reference = reference_rollout("residual_orbit", 5, 4000, "hold")
    final = reference["steps"][-1]
    assert final["truncated"] is True
    assert final["terminated"] is False

    actual = replay(reference)
    assert actual[-1][3] is True, "Python side did not report truncated"
    assert actual[-1][2] is False, "Python side reported a timeout as a failure"


def test_step_rejects_a_mis_sized_action():
    env = ml_planes._core._Env("level_hold")
    env.reset()
    with pytest.raises(ValueError, match="expected 4 actions"):
        env.step([0.0, 0.0])


def test_unknown_task_raises():
    with pytest.raises(ValueError, match="barrel_roll"):
        ml_planes._core._Env("barrel_roll")


def test_env_is_not_part_of_the_public_package_surface():
    """`_Env` is a parity harness, not the binding. Publishing it would settle the
    open question of what `reset()` should return by accident."""
    assert not hasattr(ml_planes, "_Env")
    assert "_Env" not in ml_planes.__all__
